[build-system]
requires = [
  "setuptools",
  "wheel",
  "oldest-supported-numpy",
  "Cython",
]
build-backend = "setuptools.build_meta"

[project]
name = "coniferest"
version = "0.0.10"
description = "Coniferous forests for better machine learning"
readme = "README.md"
requires-python = ">=3.7"
authors = [
  { name = "Vladimir Korolev", email = "balodja@gmail.com" },
  { name = "SNAD team" },
]
license = { text = "MIT" }
classifiers =  [
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS",
  "Programming Language :: Python",
  "Topic :: Scientific/Engineering",
]
dependencies = [
  "click",
  # We need it for cpu_count() only, but we have it anyway as a dependency of scikit-learn
  "joblib",
  "numpy",
  "scikit-learn>=1,<2",
  "matplotlib",
]

[project.urls]
"Source Code" = "https://github.com/snad-space/coniferest"

[tool.black]
line-length = 120
target-version = ["py38"]
include = '\.py$'
exclude = '''
     /(
       dist
       | build
       | \.tox
     )/
'''

[tool.ruff]
line-length = 120
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001"
]
target-version = "py38"

[tool.setuptools.packages.find]
exclude = [
  "tests",
  "notebooks",
  "notes",
]

# pytest
[tool.pytest.ini_options]
testpaths = [
  "tests",
]
markers = [
  "e2e",
  "long",
  "regression",
]
addopts = "-m 'not long'"
