name: Test

on: [push, pull_request]


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tox
      run: pipx run tox -e py${{ matrix.python-version }}

  bench:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install the package
      run: python3.11 -m pip install -e '.[dev]'
    - name: Run benchmarks
      run: python3.11 -m pytest --benchmark-enable -m benchmark --benchmark-json output.json
    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'pytest'
        output-file-path: output.json
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Comment commits at benchmark alerts
        comment-on-alert: true
        # And notify this user about the problem
        # alert-comment-cc-users: '@matwey'
        # Comment PRs
        summary-always: true
